Freeze flexsearch version to prevent breaking api change
poloclub/wizmap pull request #21
Opened 2024-02-07 19:53 UTC by fredhohman

New installs of flexsearch had a breaking API change for a patch version bump. This freezes the version. Need to slightly modify flexsearch `Index` if wanting to use latest version.

2024-02-07 20:16 UTC, xiaohk commented on package.json
> +    "flexsearch": "0.7.31",
Thanks @fredhohman!! 🙏 I just noticed that we should probably also freeze `@types/flexsearch`.

2024-02-07 20:17 UTC, xiaohk requested changes
Thanks @fredhohman!! 🙏 I just noticed that we should probably also freeze `@types/flexsearch`.

2024-02-07 22:21 UTC, fredhohman commented
@xiaohk done!

2024-02-08 01:09 UTC, merged

2024-02-08 01:09 UTC, xiaohk commented
Thank you so much!